
USE [master]
GO

/****** Object:  Database [AkqaDataStore]    Script Date: 2/26/2018 9:02:21 PM ******/
CREATE DATABASE [AkqaDataStore]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AkqaDataStore', FILENAME = N'/var/opt/mssql/data/AkqaDataStore.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'AkqaDataStore_log', FILENAME = N'/var/opt/mssql/data/AkqaDataStore_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [AkqaDataStore] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AkqaDataStore].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AkqaDataStore] SET ANSI_NULL_DEFAULT OFF
GO

ALTER DATABASE [AkqaDataStore] SET ANSI_NULLS OFF
GO

ALTER DATABASE [AkqaDataStore] SET ANSI_PADDING OFF
GO

ALTER DATABASE [AkqaDataStore] SET ANSI_WARNINGS OFF
GO

ALTER DATABASE [AkqaDataStore] SET ARITHABORT OFF
GO

ALTER DATABASE [AkqaDataStore] SET AUTO_CLOSE OFF
GO

ALTER DATABASE [AkqaDataStore] SET AUTO_SHRINK OFF
GO

ALTER DATABASE [AkqaDataStore] SET AUTO_UPDATE_STATISTICS ON
GO

ALTER DATABASE [AkqaDataStore] SET CURSOR_CLOSE_ON_COMMIT OFF
GO

ALTER DATABASE [AkqaDataStore] SET CURSOR_DEFAULT  GLOBAL
GO

ALTER DATABASE [AkqaDataStore] SET CONCAT_NULL_YIELDS_NULL OFF
GO

ALTER DATABASE [AkqaDataStore] SET NUMERIC_ROUNDABORT OFF
GO

ALTER DATABASE [AkqaDataStore] SET QUOTED_IDENTIFIER OFF
GO

ALTER DATABASE [AkqaDataStore] SET RECURSIVE_TRIGGERS OFF
GO

ALTER DATABASE [AkqaDataStore] SET  DISABLE_BROKER
GO

ALTER DATABASE [AkqaDataStore] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO

ALTER DATABASE [AkqaDataStore] SET DATE_CORRELATION_OPTIMIZATION OFF
GO

ALTER DATABASE [AkqaDataStore] SET TRUSTWORTHY OFF
GO

ALTER DATABASE [AkqaDataStore] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO

ALTER DATABASE [AkqaDataStore] SET PARAMETERIZATION SIMPLE
GO

ALTER DATABASE [AkqaDataStore] SET READ_COMMITTED_SNAPSHOT OFF
GO

ALTER DATABASE [AkqaDataStore] SET HONOR_BROKER_PRIORITY OFF
GO

ALTER DATABASE [AkqaDataStore] SET RECOVERY FULL
GO

ALTER DATABASE [AkqaDataStore] SET  MULTI_USER
GO

ALTER DATABASE [AkqaDataStore] SET PAGE_VERIFY CHECKSUM
GO

ALTER DATABASE [AkqaDataStore] SET DB_CHAINING OFF
GO

ALTER DATABASE [AkqaDataStore] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF )
GO

ALTER DATABASE [AkqaDataStore] SET TARGET_RECOVERY_TIME = 60 SECONDS
GO

ALTER DATABASE [AkqaDataStore] SET DELAYED_DURABILITY = DISABLED
GO

EXEC sys.sp_db_vardecimal_storage_format N'AkqaDataStore', N'ON'
GO

ALTER DATABASE [AkqaDataStore] SET QUERY_STORE = OFF
GO

USE [AkqaDataStore]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

USE [AkqaDataStore]
GO

/****** Object:  Table [dbo].[UserAmount]    Script Date: 2/26/2018 9:02:22 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

USE [master]
GO

ALTER DATABASE [AkqaDataStore] SET  READ_WRITE
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;

GO

--Syntax Error: Incorrect syntax near IDENTITY_CACHE.
--ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;



GO
